stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy-staging
  - deploy-production

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - |
      echo '{
        "auths": {
          "$CI_REGISTRY": {
            "username": '$CI_DEPLOY_USER',
            "password": '$CI_DEPLOY_PASSWORD'
          },
          "https://index.docker.io/v1/": {
            "username": '$DOCKERHUB_USERNAME',
            "password": '$DOCKERHUB_PASSWORD'
          }
        }
      }' > /kaniko/.docker/config.JSON
    - cat /kaniko/.docker/config.JSON
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"  
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/front:${CI_COMMIT_TAG:-latest}"

deploy-staging:
  stage: deploy-staging
  image:
    name: gcr.io/k8s-skaffold/skaffold:v2.8.0
    entrypoint: ['']
  script:
    - kubectl config use-context $K8S_CONTEXT_STAGING
    - kubectl delete secret regcred || true 
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - skaffold deploy --profile staging --images ${CI_REGISTRY_IMAGE}/front:${CI_COMMIT_TAG:-latest}
    - kubectl get all
    - kubectl get ingress

deploy-production:
  stage: deploy-production
  image:
    name: gcr.io/k8s-skaffold/skaffold:v2.8.0
    entrypoint: ['']
  when: manual
  script:
    - kubectl config use-context $K8S_CONTEXT
    - kubectl delete secret regcred || true
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - skaffold deploy --profile production --images ${CI_REGISTRY_IMAGE}/front:${CI_COMMIT_TAG:-latest}
    - kubectl get all
    - kubectl get ingress
