apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: data
  name: data
spec:
  ports:
    - protocol: TCP
      port: 6000           # Expose externally on port 6000
      targetPort: 8080     # Internal container port (same as auth)
  selector:
    deployment.name: data
status: 
  loadBalancer: {} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment.name: data
  template:
    metadata:
      labels:
        deployment.name: data
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox
        command: ["sh", "-c", "echo Waiting for RabbitMQ; sleep 10"]
      containers:
      - name: data
        image: gitlab.lnu.se:5050/2dv013/student/team-2024-03-pikachu/data-services/data-service:latest
        env:
        - name: JWT_SECRET
          value: "sdlkajdsosdihgsaoifdghasöfbnasdöfiubvhsdfiuhvnbsdpifubhdfihn"
        - name: POSTGRES_HOST
          value: "postgresql-0.postgresql-service"
        - name: POSTGRES_REPLICATION_HOST
          value: "postgresql-1.postgresql-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "let-me-in"
        - name: POSTGRES_DATABASE
          value: "postgres"
        - name: POSTGRES_REPLICATION_PORT
          value: "5432"
        - name: RABBITMQ_HOST
          value: rabbitmq.default.svc.cluster.local
        - name: RABBITMQ_PORT
          value: "5672"
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred
