apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
          resources:
            # Define the requested resources (minimum resources Kubernetes will guarantee for the container)
            requests:
              memory: "512Mi"   # Request 512 MiB of memory
              cpu: "500m"       # Request 500 milli-CPU (half of a CPU core)
            # Define the limits (maximum resources the container can use)
            limits:
              memory: "1Gi"     # Limit memory to 1 GiB
              cpu: "1"          # Limit CPU to 1 full CPU core
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP  # Exposes the service within the cluster
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Can be set to Retain, Recycle, or Delete
  hostPath:
    path: /mnt/data/rabbitmq  # Adjust path based on your environment, this is an example
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed
