apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: auth
  name: auth
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
  selector:
    deployment.name: auth
status: 
  loadBalancer: {} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment.name: auth
  template:
    metadata:
      labels:
        deployment.name: auth
    spec:
      containers:
      - name: auth
        image: gitlab.lnu.se:5050/2dv013/student/team-2024-03-pikachu/authentication/auth:latest
        env:
        - name: JWT_SECRET
          value: "sdlkajdsosdihgsaoifdghasöfbnasdöfiubvhsdfiuhvnbsdpifubhdfihn"
        - name: JWT_EMAIL_ENCRYPTION
          value: "djsdöjghsdöjghsödfghsfoigh"
        - name: POSTGRES_HOST
          value: "postgresql-0.postgresql-service"  #Matches the Service name
        - name: POSTGRES_REPLICATION_HOST
          value: "postgresql-1.postgresql-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "let-me-in"
        - name: POSTGRES_DATABASE
          value: "postgres"
        - name: POSTGRES_REPLICATION_PORT
          value: "5432"
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred # Secret set as a secret in the cluster
